# Generated by Django 4.2.30 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CREDIT_CARD", "Credit Card"),
                    ("DEBIT_CARD", "Debit Card"),
                    ("CASH", "Cash on Delivery"),
                    ("WALLET", "Wallet Balance"),
                ],
                max_length=20,
            ),
        ),
    ]
