# Generated by Django 4.2.30 on 2026-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
