"""
Async Celery tasks for users app — Requirement 3: Asynchronous Queues
═══════════════════════════════════════════════════════════════════════
Emails are sent ASYNCHRONOUSLY — registration response returns instantly,
Celery delivers the welcome email in the background.
"""

import logging
from celery import shared_task
from django.core.mail import send_mail
from django.conf import settings

logger = logging.getLogger(__name__)


@shared_task(bind=True, max_retries=3, default_retry_delay=60)
def send_welcome_email(self, user_id: int):
    """
    Asynchronous Processing (Requirement 3):
    Send a welcome email AFTER the registration response is returned.

    Flow:
      1. POST /api/users/register/  → user created → returns 201
      2. send_welcome_email.delay(user.id)  ← fires here (async)
      3. Celery worker sends the email via Mailtrap
      4. User receives welcome email — without slowing down registration
    """
    from django.contrib.auth import get_user_model
    User = get_user_model()

    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        logger.error("[EMAIL] User #%s not found — skipping welcome email", user_id)
        return

    body = f"""Hello {user.name},

Welcome to our High-Performance E-Commerce Platform! 🚀

Your account has been created successfully.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account Details
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Email:    {user.email}
Joined:   {user.created_at.strftime('%Y-%m-%d %H:%M UTC')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You can now browse products, add items to your cart,
and complete purchases on our platform.

Happy shopping!

[Async Processing — Requirement 3]
This email was generated by a Celery worker AFTER the
registration API returned 201. Your sign-up was not
delayed waiting for this email to be sent.
"""

    try:
        send_mail(
            subject="Welcome to E-Commerce Platform!",
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=False,
        )
        logger.info("[EMAIL] Welcome email sent to %s (user #%s)", user.email, user_id)

    except Exception as exc:
        logger.error("[EMAIL] Welcome email failed for user #%s (%s): %s", user_id, user.email, exc)
        raise self.retry(exc=exc)


@shared_task(bind=True, max_retries=3, default_retry_delay=60)
def send_password_reset_email(self, user_id: int, reset_token: str):
    """
    Async password reset email.
    Token generated synchronously, email delivery is async.
    """
    from django.contrib.auth import get_user_model
    User = get_user_model()

    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        return

    body = f"""Hello {user.name},

You requested a password reset.

Reset Token: {reset_token}

If you did not request this, please ignore this email.

[Async Processing — Requirement 3]
"""

    try:
        send_mail(
            subject="Password Reset Request",
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=False,
        )
        logger.info("[EMAIL] Password reset email sent to %s", user.email)
    except Exception as exc:
        logger.error("[EMAIL] Password reset email failed for user #%s: %s", user_id, exc)
        raise self.retry(exc=exc)
