"""
Async Celery tasks for orders app — Requirement 3: Asynchronous Queues
═══════════════════════════════════════════════════════════════════════
All tasks here are FIRE-AND-FORGET:
  - The checkout HTTP response is returned to the user IMMEDIATELY.
  - These tasks run in a Celery worker AFTER the response is sent.
  - The user never waits for email delivery or invoice processing.

This is the core proof of Requirement 3:
  HTTP response time ≈ DB transaction time  (fast)
  Email delivery time = separate async task  (doesn't block user)
"""

import logging
from celery import shared_task
from django.core.mail import send_mail
from django.conf import settings

logger = logging.getLogger(__name__)


@shared_task(bind=True, max_retries=3, default_retry_delay=60, rate_limit="10/m")
def send_order_confirmation_email(self, order_id: int):
    """
    Asynchronous Processing (Requirement 3):
    Send an order confirmation email AFTER the checkout response is returned.

    Flow:
      1. POST /api/orders/checkout/  → Django creates order → returns 201
      2. send_order_confirmation_email.delay(order.id)  ← fires here (async)
      3. Celery worker picks it up, builds email, sends via Mailtrap
      4. User receives email in Mailtrap inbox

    The user sees the 201 response in milliseconds.
    The email arrives seconds later — completely decoupled.

    Retry logic (Requirement 3 best practice):
      If Mailtrap is temporarily unavailable, retries up to 3 times
      with 60-second delays — without affecting the user's checkout.
    """
    from apps.orders.models import Order

    try:
        order = Order.objects.prefetch_related("items__product").get(id=order_id)
    except Order.DoesNotExist:
        logger.error("[EMAIL] Order #%s not found — skipping confirmation email", order_id)
        return

    user  = order.user
    items = order.items.all()

    # ── Build email body ───────────────────────────────────────────────────────
    items_lines = "\n".join([
        f"  • {item.product.name}  x{item.quantity}  @ {item.unit_price} = {item.unit_price * item.quantity}"
        for item in items
    ])

    body = f"""Hello {user.name},

Your order has been confirmed! 🎉

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Order Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Order ID:     #{order.id}
Status:       {order.status}
Date:         {order.created_at.strftime('%Y-%m-%d %H:%M UTC')}

Items:
{items_lines}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total:        {order.total_price} SAR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Thank you for shopping with us!

[Async Processing — Requirement 3]
This email was generated by a Celery worker AFTER
the checkout API returned 201. Your request was not
delayed waiting for this email to be sent.
"""

    try:
        send_mail(
            subject=f"Order Confirmed — #{order.id}",
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=False,
        )
        logger.info(
            "[EMAIL] Order confirmation sent to %s for Order #%s",
            user.email, order.id,
        )

    except Exception as exc:
        logger.error(
            "[EMAIL] Failed to send confirmation for Order #%s to %s: %s",
            order.id, user.email, exc,
        )
        # Retry up to 3 times (Requirement 3 — resilient async processing)
        raise self.retry(exc=exc)


@shared_task(bind=True, max_retries=3, default_retry_delay=60)
def send_order_cancelled_email(self, order_id: int):
    """
    Notify user asynchronously when their order is cancelled.
    Same pattern: response returned first, email sent by Celery after.
    """
    from apps.orders.models import Order

    try:
        order = Order.objects.get(id=order_id)
    except Order.DoesNotExist:
        return

    user = order.user

    body = f"""Hello {user.name},

Your order #{order.id} has been cancelled.

If you did not request this cancellation or have questions,
please contact our support team.

[Async Processing — Requirement 3]
"""

    try:
        send_mail(
            subject=f"Order Cancelled — #{order.id}",
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=False,
        )
        logger.info("[EMAIL] Cancellation email sent to %s for Order #%s", user.email, order.id)
    except Exception as exc:
        logger.error("[EMAIL] Cancellation email failed for Order #%s: %s", order.id, exc)
        raise self.retry(exc=exc)


@shared_task
def update_order_status_task(order_id: int, new_status: str):
    """Update order status asynchronously (e.g. after payment webhook)."""
    from apps.orders.models import Order
    try:
        Order.objects.filter(id=order_id).update(status=new_status)
        logger.info("[TASK] Order #%s status updated to %s", order_id, new_status)
    except Exception as exc:
        logger.error("[TASK] Failed to update Order #%s: %s", order_id, exc)
