# Generated by Django 4.2.30 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=500.0,
                help_text="رصيد المحفظة — يُستخدم لمحاكاة الدفع (  Payment Simulation)",
                max_digits=10,
            ),
        ),
    ]
